// example/test.tsx
import React, { type FC, useState } from 'react'

const Com: FC = () => {
    const [msg, setMsg] = useState<string>('')

    return (
        <>
            <div className="container">{msg}</div>
            <button onClick={() => setMsg('hello world!')}>setMsg</button>
        </>
    )
}

export default Com

// example/test-vue3.vue
<script setup lang="ts">
import { ref } from 'vue'
const msg = ref<string>('hello world')

const setMsg = () => {
    msg.value = 'hello R_h_zero'
}
</script>

<template>
    <div id="xx" class="xxx">{{ msg }}</div>
    <button v-if="msg === ''" @click="setMsg">setMsg</button>
</template>

<style scoped lang="scss">
.content {
    background-color: pink;
}
</style>
